name: opensuse-tumbleweed64

on:
  schedule:
    - cron: '0 0 * * MON'

jobs:
  build:
    if: github.repository == 'puppylinux-woof-CE/woof-CE'
    uses: ./.github/workflows/build.yml
    with:
      repo: ${{ github.repository }}
      ref: ${{ github.ref }}
      arch: x86_64
      compat-distro: opensuse
      compat-distro-version: tumbleweed64
      kernel: 6.6.x
      artifact: ${{ github.workflow }}-${{ github.run_number }}
      retention: 15
